#!/bin/bash
set -xe

GO_VERSION=go1.7
GO_PKG_LINUX=${GO_VERSION}.linux-amd64.tar.gz
GO_PKG_LINUX_SHA=702ad90f705365227e902b42d91dd1a40e48ca7f67a2f4b2fd052aaa4295cd95

ROOTDIR="$(cd "$(dirname $0)/.." && pwd)"
cd $ROOTDIR

GODIR="$ROOTDIR/.setup/go17"
export GOROOT="$GODIR/go"
export GOPATH="$ROOTDIR/.setup/gopath"
export PATH="$GOROOT/bin:$PATH"

# Check if local install exists, and install otherwise.
if [ -z "$(which go)" ] || [ -z "$(go version | grep $GO_VERSION)" ]; then
  [ -d "$GODIR" ] && rm -rf $GODIR
  mkdir -p "$GODIR"
  cd "$GODIR";

  curl -L -O https://storage.googleapis.com/golang/$GO_PKG_LINUX
  shasum -a256 $GO_PKG_LINUX | grep $GO_PKG_LINUX_SHA
  tar xf $GO_PKG_LINUX

  echo "$GO_VERSION installed in $GODIR: Go Binary: $(which go)"
fi

GH_PATH="$GOPATH/src/github.com/github"
PROJECT_NAME=${PROJECT_NAME:-$(basename $ROOTDIR)}

mkdir -p $GH_PATH
ln -sf "$ROOTDIR" "$GH_PATH/$PROJECT_NAME"

cd "$GH_PATH/$PROJECT_NAME"
